# Generated by Django 6.0.2 on 2026-03-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_itempedido_pedido_tamanho_delete_pizza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bordas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrecoPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriasabor')),
            ],
        ),
        migrations.DeleteModel(
            name='Acompanhamentos',
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='preco',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão de Crédito/Débito'), ('PIX', 'Pix')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bebidas',
            field=models.ManyToManyField(blank=True, to='pedidos.bebidas'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bordas',
            field=models.ManyToManyField(blank=True, to='pedidos.bordas'),
        ),
        migrations.AddField(
            model_name='sabores',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sabores', to='pedidos.categoriasabor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precopizza',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tamanho'),
        ),
        migrations.AlterUniqueTogether(
            name='precopizza',
            unique_together={('categoria', 'tamanho')},
        ),
    ]
